[toolchain]
package_manager = "pnpm"
anchor_version = "0.31.1"
solana_version = "2.2.20"

[features]
resolution = true
skip-lint = false
#seeds = false

[programs.localnet]
future_option_market = "CgZEcSRPh1Ay1EYR4VJPTJRYcRkTDjjZhBAjZ5M8keGp"
[programs.devnet]
future_option_market = "CgZEcSRPh1Ay1EYR4VJPTJRYcRkTDjjZhBAjZ5M8keGp"
[programs.mainnet]
future_option_market = "CgZEcSRPh1Ay1EYR4VJPTJRYcRkTDjjZhBAjZ5M8keGp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
#cluster = "Devnet"
#cluster = "Mainnet"

[test]
startup_wait = 5000
shutdown_wait = 2000
#upgradeable = false

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
